name: "CI"

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  unit-test:
    name: Unit test using ${{matrix.rust}}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        rust: [1.66, nightly, beta, stable]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.rust}}
      - name: Run unit tests
        run: |
          just test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - name: Run lint
        run: |
          just lint
