name: "Release"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

env:
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  publish-image:
    name: Publish image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Image
        run: |
          just image ${{ env.IMAGE_TAG }} image_repo=${{ env.IMAGE_NAME }}
      - name: Publish image
        run: |
          export DOCKER_IMAGE=${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          export GHCR_IMAGE=ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          
          docker tag ${DOCKER_IMAGE} ${GHCR_IMAGE}
          
          docker push ${GHCR_IMAGE}
          docker manifest create ${GHCR_IMAGE} ${GHCR_IMAGE}
          docker manifest push ${GHCR_IMAGE}
          
          docker push ${DOCKER_IMAGE}
          docker manifest create ${DOCKER_IMAGE} ${DOCKER_IMAGE}
          docker manifest push ${DOCKER_IMAGE}